=== forward-seen/sparrow-shell/sparrow-mvc/src/main/resources/mvc.dtd
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one or more
  ~ contributor license agreements.  See the NOTICE file distributed with
  ~ this work for additional information regarding copyright ownership.
  ~ The ASF licenses this file to You under the Apache License, Version 2.0
  ~ (the "License"); you may not use this file except in compliance with
  ~ the License.  You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

        <!--
             MyEclipse config method:
             Preference->MyEclipse->Files and Editors->XML->
             XML Catalog->Add
             1)Location: .dtd file address
             2)Key Type: URI
             3)Key     : http://www.sparrowzoo.com/dtds/mvc-config.dtd
             DTD for the mvc Configuration File

             To support validation of your configuration file, include the following
             DOCTYPE element at the beginning (after the "xml" declaration):
             <!DOCTYPE mvc-config PUBLIC "-//sparrow Framework//DTD mvc Configuration//EN"
             "http://www.sparrowzoo.com/dtds/mvc-config.dtd">
             $Id: mvc-config.dtd $
        -->
        <!ELEMENT mvc (controller*)>
        <!ELEMENT controller (action+)>
        <!ELEMENT action (result*)>
        <!ELEMENT result (#PCDATA)>

        <!ATTLIST result
                name (success|error)  #IMPLIED>

        <!--@see com.sparrow.enums.LoginType-->
        <!ATTLIST action
                name   CDATA #REQUIRED
                method CDATA #IMPLIED
                login  (NO_AUTHENTICATE|LOGIN|LOGIN_IFRAME|DIALOG_LOGIN|MESSAGE) #IMPLIED
                needAuthorizing (true|false) #IMPLIED
                validateRequest (true|false) #IMPLIED>

        <!ATTLIST controller
                id CDATA #REQUIRED>

=== forward-seen/sparrow-shell/sparrow-test/src/main/resources/controller.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mvc PUBLIC "-//sparrow Framework//DTD mvc Configuration//EN"
    "http://www.sparrowzoo.com/dtds/mvc.dtd">
<mvc>
    <!--在bean context中定义-->
    <controller id="helloController">
        <!--/template/index.jsp 兼容欢迎页-->
        <action name="/template/welcome.jsp" method="welcome"/>
        <!---一定以 /开头-->
        <action name="/hello" method="hello" login="NO_AUTHENTICATE"/>
        <action name="/fly" method="fly"/>
        <action name="/transit-test" method="transit">
            <result name="success">transit-here</result>
        </action>
        <action name="/thread-{threadId}-{pageIndex}" method="thread"/>
        <action name="/json-test.json" method="json"/>
        <action name="/exception" method="exception"/>
        <action name="/exception.json" method="exception"/>
        <action name="/authorizing" method="authorizing"
                login="LOGIN" needAuthorizing="true"/>
        <action name="/login.do" method="login"/>
        <action name="/pager.json" method="pager"/>

    </controller>

    <controller id="elasticSearchController">
        <action name="/elastic/search/mapping.json" method="mapping"/>
        <action name="/elastic/search/analyze.json" method="analyze"/>
        <action name="/elastic/search/tokenize.json" method="tokenize"/>
        <action name="/elastic/search/info.json" method="info"/>
        <action name="/elastic/search/mapping-create.json" method="mappingCreate"/>
    </controller>

    <controller id="classLoaderController">
        <action name="/class-loader/get-parent" method="getParent"/>
    </controller>
</mvc>
